include("${CMAKE_CURRENT_LIST_DIR}/functions.cmake")

set(CMAKE_PROJ_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/tl_zigbee_sdk/apps")
set(CMAKE_SDK_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/tl_zigbee_sdk")
set(TL_CHECK_FW_TOOL "${CMAKE_SDK_SOURCE_DIR}/tools/tl_check_fw2.out")

set(TELINK_APP "sampleSwitch" CACHE STRING "Telink sample application")
set_property(CACHE TELINK_APP PROPERTY STRINGS sampleSwitch sampleGW)

if(TELINK_APP STREQUAL "sampleSwitch")
    set(TELINK_APP_SOURCE_DIR sampleSwitch)
    set(TELINK_PROJECT_NAME sampleSwitch_8258)
    set(TELINK_EQUIP_TYPE ZED)
    set(TELINK_ROLE_DEFINE END_DEVICE)
    set(TELINK_PROJECT_DEFINE __PROJECT_TL_SWITCH__)
elseif(TELINK_APP STREQUAL "sampleGW")
    set(TELINK_APP_SOURCE_DIR sampleGW)
    set(TELINK_PROJECT_NAME sampleGW_8258)
    set(TELINK_EQUIP_TYPE ZC)
    set(TELINK_ROLE_DEFINE COORDINATOR)
    set(TELINK_PROJECT_DEFINE __PROJECT_TL_GW__)
else()
    message(FATAL_ERROR "Unsupported TELINK_APP: ${TELINK_APP}")
endif()

set(TELINK_MCU_CORE 8258)
set(TELINK_LINKER_SCRIPT "${CMAKE_SDK_SOURCE_DIR}/platform/boot/8258/boot_8258.link")

if(DEFINED TC32_TOOLCHAIN_PATH AND NOT TC32_TOOLCHAIN_PATH STREQUAL "")
    set(TELINK_TOOLCHAIN_PATH "${TC32_TOOLCHAIN_PATH}")
elseif(DEFINED ENV{TC32_TOOLCHAIN_PATH} AND NOT "$ENV{TC32_TOOLCHAIN_PATH}" STREQUAL "")
    set(TELINK_TOOLCHAIN_PATH "$ENV{TC32_TOOLCHAIN_PATH}")
elseif(DEFINED ENV{TELINK_TOOLCHAIN_PATH} AND NOT "$ENV{TELINK_TOOLCHAIN_PATH}" STREQUAL "")
    set(TELINK_TOOLCHAIN_PATH "$ENV{TELINK_TOOLCHAIN_PATH}")
else()
    set(TELINK_TOOLCHAIN_PATH "tc32-elf-")
endif()

set(TELINK_COMPILE_DEFINITIONS
    MCU_CORE_8258=1
    MCU_STARTUP_8258=1
    ${TELINK_ROLE_DEFINE}=1
    ${TELINK_PROJECT_DEFINE}=1
)

check_vars(
    TELINK_APP
    TELINK_APP_SOURCE_DIR
    TELINK_PROJECT_NAME
    TELINK_MCU_CORE
    TELINK_LINKER_SCRIPT
    TELINK_EQUIP_TYPE
    TELINK_ROLE_DEFINE
    TELINK_PROJECT_DEFINE
    TELINK_TOOLCHAIN_PATH
)
