function(check_vars)
    foreach(var_name IN LISTS ARGV)
        if(DEFINED ${var_name})
            message(STATUS "${var_name}: ${${var_name}}")
        else()
            message(FATAL_ERROR "${var_name} is not defined")
        endif()
    endforeach()
endfunction()
